### ISSUE TITLE
Getting API errors

### ISSUE THREAD

**Issue by dprentis** [freeedcom/ai-codereviewer#7]
First of all thanks for working on this github action - it's an amazing idea! :+1:

I'm having problems getting it to work - on most PRs it throws an API error. It looks like there's an issue generating the comments, which are sent to the github api.

Here is an example error:
```
Error: SyntaxError: Unexpected token ` in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/runner/work/_actions/freeedcom/ai-codereviewer/v2.1.0/webpack:/open-ai-reviewer/lib/main.js:146:1
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/freeedcom/ai-codereviewer/v2.1.0/webpack:/open-ai-reviewer/lib/main.js:28:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: RequestError [HttpError]: Unprocessable Entity: "Pull request review thread path is invalid and Pull request review thread diff hunk can't be blank"
    at /home/runner/work/_actions/freeedcom/ai-codereviewer/v2.1.0/webpack:/open-ai-reviewer/node_modules/@octokit/request/dist-node/index.js:78:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 422,
...
 ```

**Comment by dprentis** [comment]
This is possibly caused by an invalid file path value. There are some comments in the request with `/dev/null` as the path, eg:
```
{
  "body": "Consider adding a comment to explain the purpose of the `router` object.",
  "path": "/dev/null",
  "line": 31
},
```

**Comment by dprentis** [comment]
So I guess this happens when the PR deletes a file - you should probably filter out any comments where `file.to === '/dev/null'`

**Comment by dprentis** [comment]
Workaround is to add `/dev/null` to the exlcude setting in the yml file.

**Comment by villesau** [comment]
@dprentis thanks for reporting and debugging the issue! Indeed I probably haven't had yet situation where i've deleted a file so I haven't encountered the issue either. I probably check this out in the coming days. But as you already seem to be on top of the issue, don't hesitate to open a pull request!

**Comment by villesau** [comment]
In the spirit of this repo, I pasted the code and this issue thread to gpt-4 and let it to fix the issue for us :) btw. If you have ideas for prompt on how to discourage the bot to suggest commenting on code even more strongly, I'm all ears!

**Comment by dprentis** [comment]
Thanks for the fix! :+1: Another solution might be to filter out directly here:
https://github.com/freeedcom/ai-codereviewer/blob/main/src/main.ts#L199

Something like:
```
const filteredDiff = parsedDiff.filter((file) => {
    return file.to !== '/dev/null' && !excludePatterns.some((pattern) =>
      minimatch(file.to ?? "", pattern)
    );
  });
```
Regarding blocking comments, possibly you could try somehow filter the bots output - but that might be a bit fragile :shrug:

Generally there are other limitations:
1) bot only sees the diffs, not the whole repo, so it doesn't have enough context to do an indepth review
2) bot processes individual diffs, and so eg. it doesn't know about the last diff when it processes the first one
 
Anyway, it's a great idea and likely to become really useful as the bot develops - good luck :+1: :smile:

**Comment by villesau** [comment]
> Thanks for the fix! 👍 Another solution might be to filter out directly here:

Thanks! That could indeed be a better place, but I'm really tempted to let gpt-4 to develop this bot forward (and review it's own code along the way! 😅). Most of the bot code is actually written by gpt-4. I've only written some harder concepts (line numbers for diffs etc) and the actual prompts. Even the readme is fully generated by gpt-4 just based on the main.ts code I've pasted to it.

> bot only sees the diffs, not the whole repo, so it doesn't have enough context to do an indepth review
bot processes individual diffs, and so eg. it doesn't know about the last diff when it processes the first one

This is what I've been thinking about. It is a balance between the prompt size and amount of context. Now it only reviews individual diff chunks, not even the whole pull requests at once. We could add all the diffs of the PR and pinpoint (e.g duplicate) the actual diff to review, but bigger PRs could start to fail, and too much context might actually be harmful and I've seen gpt-4 to get lost in the woods with too much context as well. Also, the bigger the prompt, the more costly it gets. gpt-4 is surprisingly pricey.

First stab was to include the PR description as a context. I'm also thinking on adding e.g some sort of dependency-graph or file structure in the prompt but not sure if they are much help. Somehow including more, if not all, from the PR could also make sense.

**Comment by peterjurkovic** [comment]
Hello, I am getting this error as well with `v2.7.0`

```
Run freeedcom/ai-codereviewer@v2.7.0
Error: SyntaxError: Unexpected token ` in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/runner/work/_actions/freeedcom/ai-codereviewer/v2.7.0/webpack:/open-ai-reviewer/lib/main.js:151:1
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/freeedcom/ai-codereviewer/v2.7.0/webpack:/open-ai-reviewer/lib/main.js:28:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
